name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build ./Exercise2 --file ./Exercise2/Dockerfile --tag proiectinternship:${{ env.COMMIT_HASH }}

    - name: Push to Docker Hub
      run: docker tag proiectinternship:${{ env.COMMIT_HASH }} ${{ secrets.DOCKER_USERNAME }}/proiectinternship:${{ env.COMMIT_HASH }} &&
           docker push ${{ secrets.DOCKER_USERNAME }}/proiectinternship:${{ env.COMMIT_HASH }}
